server:
  port: 8000
spring:
  application:
    name: chatpot
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      model: gpt-3.5-turbo

    vertex:
      ai:
        gemini:
          project-id: ${GEMINI_PROJECT_ID}
          location: asia-northeast3
          options:
            model: gemini-1.5-flash-001
chat:
  system:
    message: ${CHAT_SYSTEM_MESSAGE}
